//
//  EmpathyServiceProtocol.swift
//  VoiceVault
//
//  Created by VoiceVault Team on 4/25/26.
//  Hackathon Day 1 — Service Contract: Empathetic Response Generation
//

import Foundation

// MARK: - EmpathyError

/// Errors that can occur during empathetic response generation.
enum EmpathyError: Error, LocalizedError, Sendable {

    /// The on-device language model is not available on this device.
    case modelUnavailable

    /// The model failed to generate a response.
    case generationFailed(underlying: String)

    /// The provided sentiment result was invalid or empty.
    case invalidInput

    var errorDescription: String? {
        switch self {
        case .modelUnavailable:
            return "On-device language model is not available. Apple Intelligence may not be supported on this device."
        case .generationFailed(let msg):
            return "Failed to generate empathetic response: \(msg)"
        case .invalidInput:
            return "Cannot generate a response from an empty or invalid sentiment result."
        }
    }
}

// MARK: - EmpathyResponse

/// A value type containing the generated empathetic response and its metadata.
///
/// The response is always short (1-2 sentences), warm, and never contains
/// clinical terminology, numeric scores, or medical advice.
struct EmpathyResponse: Sendable, Equatable {

    /// The empathetic text generated by the on-device LLM.
    let message: String

    /// The persona mode used for generation, determined by sentiment severity.
    let mode: EmpathyMode
}

// MARK: - EmpathyMode

/// The persona mode that governs the LLM's tone and constraints.
///
/// Determined by the `SentimentResult.score`:
/// - **crisis**: score < -0.8 → Validation-only. Acknowledge pain. No advice.
/// - **distress**: score < -0.4 → Gentle support. Normalize feelings.
/// - **neutral**: score in [-0.4, 0.4] → Warm acknowledgment. Encourage reflection.
/// - **positive**: score > 0.4 → Celebrate progress. Reinforce growth.
enum EmpathyMode: String, Sendable, Equatable {
    case crisis   = "Crisis Validation"
    case distress = "Gentle Support"
    case neutral  = "Warm Acknowledgment"
    case positive = "Growth Reinforcement"
}

// MARK: - EmpathyServiceProtocol

/// Defines the contract for on-device empathetic response generation.
///
/// ## Responsibilities
/// - Accept a `SentimentResult` from the intelligence pipeline.
/// - Determine the appropriate emotional persona (crisis, distress, neutral, positive).
/// - Generate a short, warm, non-clinical response using Apple Foundation Models.
/// - Ensure all generation remains strictly on-device (Neural Engine).
///
/// ## Safety Contract
/// - MUST NOT include numeric scores, percentages, or clinical terminology.
/// - MUST NOT provide medical advice, diagnoses, or treatment suggestions.
/// - In crisis mode (score < -0.8), MUST restrict to validation-only language.
/// - The prompt MUST be "sandwiched" by the objective score and keywords.
///
/// ## Usage
/// ```swift
/// let empathy: EmpathyServiceProtocol = environment.empathyService
/// let response = try await empathy.generateResponse(for: sentimentResult)
/// print(response.message) // "I hear you. What you're feeling is real and it matters."
/// ```
protocol EmpathyServiceProtocol: Sendable {

    /// Generates an empathetic response based on the analyzed sentiment.
    ///
    /// - Parameter sentimentResult: The output from `IntelligenceService.analyze(transcript:)`.
    /// - Returns: An `EmpathyResponse` containing the message and the persona mode used.
    /// - Throws: `EmpathyError` if the model is unavailable or generation fails.
    func generateResponse(for sentimentResult: SentimentResult) async throws -> EmpathyResponse

    /// Checks whether the on-device LLM is available on the current hardware.
    ///
    /// Should be called before attempting generation to provide graceful degradation
    /// on devices that do not support Apple Intelligence.
    ///
    /// - Returns: `true` if the model is ready for inference.
    func isModelAvailable() -> Bool
}
